# Generated by Django 2.2.6 on 2019-10-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191020_0223'),
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Related post',
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='post.Post'),
        ),
    ]
