# Generated by Django 2.2.3 on 2019-09-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_currentquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresult',
            name='is_atm',
            field=models.BooleanField(default=0),
        ),
    ]
