# Generated by Django 2.2.3 on 2019-09-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20190916_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizresult',
            name='max_score',
        ),
    ]
