# Generated by Django 2.2.3 on 2019-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_userquizresult_is_atm'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentquiz',
            name='sel_ans',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
