# Generated by Django 2.2.3 on 2019-09-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_remove_userquizresult_max_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquizresult',
            old_name='quiz_title',
            new_name='quiz',
        ),
    ]
