# Generated by Django 2.2.3 on 2019-09-18 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0005_auto_20190918_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_ques_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
