# Generated by Django 2.2.3 on 2019-09-17 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190917_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 17, 19, 8, 58, 640986, tzinfo=utc)),
        ),
    ]
