# Generated by Django 2.2.6 on 2019-10-19 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191020_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 19, 20, 53, 12, 496540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 53, 12, 498231, tzinfo=utc)),
        ),
    ]
