# Generated by Django 2.2.3 on 2019-09-15 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190914_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 15, 18, 35, 2, 937789, tzinfo=utc)),
        ),
    ]
