# Generated by Django 2.2.3 on 2019-09-19 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190919_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unique_view_no',
            field=models.PositiveIntegerField(default=0, verbose_name='Unique views'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 10, 2, 14, 391929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 10, 2, 14, 393924, tzinfo=utc)),
        ),
    ]
