# Generated by Django 2.2.8 on 2019-12-31 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191020_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 31, 15, 8, 55, 1430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 15, 8, 55, 3075, tzinfo=utc)),
        ),
    ]
