# Generated by Django 2.2.3 on 2019-09-13 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190912_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 13, 10, 17, 4, 15409, tzinfo=utc)),
        ),
    ]
