# Generated by Django 2.2.3 on 2019-09-18 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190918_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 21, 22, 49, 221878, tzinfo=utc)),
        ),
    ]
