# Generated by Django 2.1.5 on 2019-07-14 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190714_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 14, 16, 9, 24, 888735, tzinfo=utc)),
        ),
    ]
