# Generated by Django 2.2.3 on 2019-09-18 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_auto_20190918_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='subscribed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Subscribed By'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 13, 24, 14, 274148, tzinfo=utc)),
        ),
    ]
