# Generated by Django 2.2.3 on 2019-09-14 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190914_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 14, 12, 24, 19, 184794, tzinfo=utc)),
        ),
    ]
