# Generated by Django 2.2.3 on 2019-09-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20190918_1854'),
        ('post', '0007_auto_20190919_0252'),
    ]

    operations = [
    ]
