# Generated by Django 2.2.3 on 2019-09-14 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20190914_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 14, 13, 9, 8, 248955, tzinfo=utc)),
        ),
    ]
