# Generated by Django 2.2.3 on 2019-09-14 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20190914_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 14, 13, 20, 56, 687594, tzinfo=utc)),
        ),
    ]
