# Generated by Django 2.2.3 on 2019-09-19 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_merge_20190919_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 21, 16, 13, 365936, tzinfo=utc)),
        ),
    ]
