# Generated by Django 2.2.3 on 2019-09-16 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20190914_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 16, 11, 20, 7, 697086, tzinfo=utc)),
        ),
    ]
