# Generated by Django 2.1.5 on 2019-07-15 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20190714_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 15, 15, 52, 31, 722274, tzinfo=utc)),
        ),
    ]
