# Generated by Django 2.2.3 on 2019-09-16 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('post', '0011_auto_20190916_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_target', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='post',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 16, 11, 36, 10, 589352, tzinfo=utc)),
        ),
    ]
