# Generated by Django 2.2.3 on 2019-09-16 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20190916_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='target_object_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 16, 11, 41, 9, 143918, tzinfo=utc)),
        ),
    ]
