# Generated by Django 2.1.5 on 2019-07-16 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20190715_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 6, 56, 29, 183515, tzinfo=utc)),
        ),
    ]
