# Generated by Django 2.1.5 on 2019-07-16 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20190716_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 7, 5, 37, 209489, tzinfo=utc)),
        ),
    ]
