# Generated by Django 2.1.5 on 2019-07-16 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20190716_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 13, 5, 2, 602961, tzinfo=utc)),
        ),
    ]
