# Generated by Django 2.2.3 on 2019-07-30 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20190730_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 30, 6, 52, 33, 111157, tzinfo=utc)),
        ),
    ]
