# Generated by Django 2.2.3 on 2019-08-19 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_auto_20190817_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 19, 18, 42, 43, 223591, tzinfo=utc)),
        ),
    ]
