# Generated by Django 2.2.3 on 2019-09-01 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_auto_20190820_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 19, 12, 24, 744301, tzinfo=utc)),
        ),
    ]
