# Generated by Django 2.2.3 on 2019-09-04 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_auto_20190902_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verify_status',
            field=models.IntegerField(default=-1, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 4, 8, 17, 46, 185729, tzinfo=utc)),
        ),
    ]
