# Generated by Django 2.2.3 on 2019-09-04 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_auto_20190904_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 4, 11, 18, 7, 180607, tzinfo=utc)),
        ),
    ]
