# Generated by Django 2.2.3 on 2019-09-07 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_auto_20190907_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 5, 4, 50, 250364, tzinfo=utc)),
        ),
    ]
