# Generated by Django 2.2.3 on 2019-09-07 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_auto_20190907_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_on_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 7, 10, 27, 12, 759670, tzinfo=utc)),
        ),
    ]
