# Generated by Django 2.2.3 on 2019-07-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20190716_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_text',
        ),
    ]
