# Generated by Django 2.2.3 on 2019-07-31 12:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190723_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Comment Text'),
        ),
    ]
