# Generated by Django 2.2.3 on 2019-07-31 12:19

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20190731_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now, verbose_name='Comment Text'),
            preserve_default=False,
        ),
    ]
