# Generated by Django 2.2.3 on 2019-09-16 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, default='default.png', null=True, upload_to=user_profile.models.user_directory_path)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('is_sound_on', models.BooleanField(default=True)),
                ('is_password_set', models.BooleanField(default=False)),
                ('is_profile_set', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
