# Generated by Django 2.1.5 on 2019-07-09 09:39

from django.db import migrations
import imagekit.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=user_profile.models.user_directory_path),
        ),
    ]
