# Generated by Django 2.2.3 on 2019-09-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190908_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_set',
            field=models.BooleanField(default=False),
        ),
    ]
