# Generated by Django 2.2.3 on 2019-09-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190709_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
