# Generated by Django 2.2.3 on 2019-09-07 05:04

from django.db import migrations
import imagekit.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default.png', null=True, upload_to=user_profile.models.user_directory_path),
        ),
    ]
