# Generated by Django 2.2.3 on 2019-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_is_profile_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_sound_on',
            field=models.BooleanField(default=True),
        ),
    ]
