# Generated by Django 2.2.3 on 2019-09-07 05:20

from django.db import migrations
import imagekit.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20190907_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=user_profile.models.user_directory_path),
        ),
    ]
