# Generated by Django 2.2.3 on 2019-09-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20190918_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_google_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
